

import 'package:moovi/database/mainViewModel.dart';
import 'package:moovi/database/movieEntity.dart';

class PopulateDatabase{

  //Ugly fix but works for now bc db is local
  static void populateDb(MainViewModel mvm) async{
      List<MovieEntity?> movies = await mvm.getAllMovies();
      if(movies.length < 100){
          _populateHelper(mvm);
      } else if (movies.length > 110){
        print("Added movies more than once :(");
        await mvm.clearMovieTable();
        _populateHelper(mvm);
      }
  }

  static void _populateHelper(MainViewModel mvm){
    mvm.addMovie("Red Notice","https://m.media-amazon.com/images/M/MV5BNmNkZDRmZmQtZTQyMy00NmVkLWE4ZTUtNjNjZWRmNmFjYzZkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","PG-13",-1,"115 min","Action, Comedy, Crime            ",2021,"Netflix","An Interpol agent tracks the world's most wanted art thief.");
    mvm.addMovie("The Guilty","https://m.media-amazon.com/images/M/MV5BZWI3NmEyYzAtNWY4OC00YWY4LTk2MjgtM2Y1NDdlZWE4ODgzXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg","R",6.3,"90 min","Crime, Drama, Thriller            ",2021,"Netflix","A demoted police officer assigned to a call dispatch desk is conflicted when he receives an emergency phone call from a kidnapped woman.");
    mvm.addMovie("The Unforgivable","https://m.media-amazon.com/images/M/MV5BM2M5MTJmOTEtNWU1Yy00NDNmLWI3MjMtNzFkN2FiZjE5Njg3XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg","R",-1,"112 min","Drama            ",2021,"Netflix","A woman is released from prison after serving a sentence for a violent crime and re-enters a society that refuses to forgive her past.");
    mvm.addMovie("Venom","https://m.media-amazon.com/images/M/MV5BNzAwNzUzNjY4MV5BMl5BanBnXkFtZTgwMTQ5MzM0NjM@._V1_.jpg","PG-13",6.7,"112 min","Action, Adventure, Sci-Fi            ",2018,"Netflix","A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.");
    mvm.addMovie("The Green Knight","https://m.media-amazon.com/images/M/MV5BMjMxNTdiNWMtOWY0My00MjM4LTkwNzMtOGI0YThhN2Q4M2I4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","R",6.6,"130 min","Adventure, Drama, Fantasy            ",2021,"Netflix","A fantasy retelling of the medieval story of Sir Gawain and the Green Knight.");
    mvm.addMovie("It","https://m.media-amazon.com/images/M/MV5BZDVkZmI0YzAtNzdjYi00ZjhhLWE1ODEtMWMzMWMzNDA0NmQ4XkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_.jpg","R",7.3,"135 min","Horror            ",2017,"Netflix","In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.");
    mvm.addMovie("The King","https://m.media-amazon.com/images/M/MV5BNjJkYjFkNDYtYjZiYS00OTQxLWFhNzUtZmVlOWMyMzgzODQzXkEyXkFqcGdeQXVyMTA3MzQ4MTcw._V1_.jpg","R",7.3,"140 min","Biography, Drama, History            ",2019,"Netflix","Hal, wayward prince and heir to the English throne, is crowned King Henry V after his tyrannical father dies. Now the young king must navigate palace politics, the war his father left behind, and the emotional strings of his past life.");
    mvm.addMovie("Army of the Dead","https://m.media-amazon.com/images/M/MV5BNGY0NzgzYzctYWQwMC00MzM2LThjNGMtZjFjMWUyNzg0ZmM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg","R",5.8,"148 min","Action, Crime, Horror            ",2021,"Netflix","Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble, venturing into the quarantine zone to pull off the greatest heist ever attempted.");
    mvm.addMovie("The Harder They Fall","https://m.media-amazon.com/images/M/MV5BYjg4NGExN2EtZmMxYy00ZDEwLWJiZGEtOWRiN2RlMGE0OWE0XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_.jpg","R",5.7,"130 min","Drama, Western            ",2021,"Netflix","When an outlaw discovers his enemy is being released from prison, he reunites his gang to seek revenge in this Western.");
    mvm.addMovie("Arrival","https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_.jpg","PG-13",7.9,"116 min","Drama, Sci-Fi            ",2016,"Netflix","A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.");
    mvm.addMovie("King Arthur: Legend of the Sword","https://m.media-amazon.com/images/M/MV5BMjM3ODY3Njc5Ml5BMl5BanBnXkFtZTgwMjQ5NjM5MTI@._V1_.jpg","PG-13",6.7,"126 min","Action, Adventure, Drama            ",2017,"Netflix","Robbed of his birthright, Arthur comes up the hard way in the back alleys of the city. But once he pulls the sword from the stone, he is forced to acknowledge his true legacy - whether he likes it or not.");
    mvm.addMovie("Hubie Halloween","https://m.media-amazon.com/images/M/MV5BMWQzOWRhNjItNmM0ZC00ZjNjLWFhNmUtM2MzZjRjYWRjMzRkXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg","PG-13",5.2,"103 min","Comedy, Mystery            ",2020,"Netflix","Despite his devotion to his hometown of Salem (and its Halloween celebration), Hubie Dubois is a figure of mockery for kids and adults alike. But this year, something is going bump in the night, and it's up to Hubie to save Halloween.");
    mvm.addMovie("Gladiator","https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg","R",8.5,"155 min","Action, Adventure, Drama            ",2000,"Netflix","A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.");
    mvm.addMovie("American Psycho","https://m.media-amazon.com/images/M/MV5BZTM2ZGJmNjQtN2UyOS00NjcxLWFjMDktMDE2NzMyNTZlZTBiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg","R",7.6,"101 min","Comedy, Crime, Drama            ",2000,"Netflix","A wealthy New York City investment banking executive, Patrick Bateman, hides his alternate psychopathic ego from his co-workers and friends as he delves deeper into his violent, hedonistic fantasies.");
    mvm.addMovie("Titanic","https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg","PG-13",7.8,"194 min","Drama, Romance            ",1997,"Netflix","A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.");
    mvm.addMovie("Don't Look Up","https://m.media-amazon.com/images/M/MV5BYTA5MzRmZDEtYTRjNi00YTc3LTllZWUtYzc1Njg2Y2YwZDljXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg","R",-1,"145 min","Comedy, Drama, Sci-Fi            ",2021,"Netflix","Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy planet Earth.");
    mvm.addMovie("Sicario","https://m.media-amazon.com/images/M/MV5BMjA5NjM3NTk1M15BMl5BanBnXkFtZTgwMzg1MzU2NjE@._V1_.jpg","R",7.6,"121 min","Action, Crime, Drama            ",2015,"Netflix","An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.");
    mvm.addMovie("The Little Things","https://m.media-amazon.com/images/M/MV5BMGYxYzBmODEtZjFjMC00OTEyLWJmNjgtY2VkYTgxMzRkMDJiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","R",6.3,"128 min","Crime, Drama, Mystery            ",2021,"Netflix","Kern County Deputy Sheriff Joe Deacon is sent to Los Angeles for what should have been a quick evidence-gathering assignment. Instead, he becomes embroiled in the search for a serial killer who is terrorizing the city.");
    mvm.addMovie("The Lord of the Rings: The Fellowship of the Ring","https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg","PG-13",8.8,"178 min","Action, Adventure, Drama            ",2001,"Netflix","A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.");
    mvm.addMovie("Kate","https://m.media-amazon.com/images/M/MV5BN2IyYzI4YmQtNzBmMi00Mjg3LWI4NTMtNmZjNjk3YjIwZmJhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","R",6.2,"106 min","Action, Adventure, Crime            ",2021,"Netflix","A female assassin has 24 hours to get vengeance on her poisoner before she dies.");
    mvm.addMovie("Zodiac","https://m.media-amazon.com/images/M/MV5BN2UwNDc5NmEtNjVjZS00OTI5LWE5YjctMWM3ZjBiZGYwMGI2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg","R",7.7,"157 min","Crime, Drama, Mystery            ",2007,"Netflix","Between 1968 and 1983, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer, an unidentified individual who terrorizes Northern California with a killing spree.");
    mvm.addMovie("Fear Street: Part One - 1994","https://m.media-amazon.com/images/M/MV5BNzQzYjIyZDQtMjBhZS00MzU3LTk0MTQtNTVmMDI3ZWY0ZWU3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","R",6.2,"107 min","Drama, Horror, Mystery            ",2021,"Netflix","A circle of teenage friends accidentally encounter the ancient evil responsible for a series of brutal murders that have plagued their town for over 300 years. Welcome to Shadyside.");
    mvm.addMovie("Passing","https://m.media-amazon.com/images/M/MV5BYTNhOTlmMDYtNWUyMi00Y2E0LThmYmItNGY4ZGI2ZDgwZmI3XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg","PG-13",6.8,"98 min","Drama            ",2021,"Netflix","Passing follows the unexpected reunion of two high school friends, whose renewed acquaintance ignites a mutual obsession that threatens both of their carefully constructed realities.");
    mvm.addMovie("Léon: The Professional","https://m.media-amazon.com/images/M/MV5BODllNWE0MmEtYjUwZi00ZjY3LThmNmQtZjZlMjI2YTZjYmQ0XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_.jpg","R",8.5,"110 min","Action, Crime, Drama            ",1994,"Netflix","Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.");
    mvm.addMovie("Jurassic Park","https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_.jpg","PG-13",8.1,"127 min","Action, Adventure, Sci-Fi            ",1993,"Netflix","A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.");
    mvm.addMovie("Gone Girl","https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_.jpg","R",8.1,"149 min","Drama, Mystery, Thriller            ",2014,"Netflix","With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.");
    mvm.addMovie("The Power of the Dog","https://m.media-amazon.com/images/M/MV5BOTY3MjRlNTctMjI3Mi00MTc3LTgwMzEtMjZhNWYyMjNkMDU0XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_.jpg","R",6.6,"126 min","Drama, Romance, Western            ",2021,"Netflix","Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed to the possibility of love.");
    mvm.addMovie("Till Death","https://m.media-amazon.com/images/M/MV5BZGE1YjdlYzUtNGRkNC00MWFmLWI3OTEtMTA4YmNiMjU2NDAwXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_.jpg","R",5.8,"88 min","Horror, Thriller            ",2021,"Netflix","A woman is left handcuffed to her dead husband as part of a sick revenge plot. Unable to unshackle, she has to survive as two killers arrive to finish her off.");
    mvm.addMovie("The Starling","https://m.media-amazon.com/images/M/MV5BZmFlMGVjNTktOWMxOC00NzdkLWE2NTMtYjE5YTdjZjAwNmRjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg","PG-13",6.3,"102 min","Comedy, Drama            ",2021,"Netflix","After Lilly suffers a loss, a combative Starling takes nest beside her quiet home. The feisty bird taunts and attacks the grief-stricken Lilly. On her journey to expel the Starling, she rediscovers her will to live and capacity for love.");
    mvm.addMovie("Spider-Man","https://m.media-amazon.com/images/M/MV5BZDEyN2NhMjgtMjdhNi00MmNlLWE5YTgtZGE4MzNjMTRlMGEwXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_.jpg","PG-13",7.3,"121 min","Action, Adventure, Sci-Fi            ",2002,"Netflix","When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.");
    mvm.addMovie("The Departed","https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_.jpg","R",8.5,"151 min","Crime, Drama, Thriller            ",2006,"Netflix","An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.");
    mvm.addMovie("Moonrise Kingdom","https://m.media-amazon.com/images/M/MV5BMzllMWI1ZDQtMmFhNS00NzJkLThmMTMtNzFmMmMyYjU3ZGVjXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_.jpg","PG-13",7.8,"94 min","Comedy, Drama, Romance            ",2012,"Netflix","A pair of young lovers flee their New England town, which causes a local search party to fan out to find them.");
    mvm.addMovie("No One Gets Out Alive","https://m.media-amazon.com/images/M/MV5BZGQzODVkZDAtOWFhNS00MWJhLThjNDctNjFlZDExYjg5NWM1XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg","R",5.3,"85 min","Drama, Horror, Mystery            ",2021,"Netflix","An immigrant in search of the American dream who, after being forced to take a room in a boarding house, finds herself in a nightmare she can't escape.");
    mvm.addMovie("Hush","https://m.media-amazon.com/images/M/MV5BOWQ4OTdlODQtMDc3Yy00MGVmLWExYjUtOGI0Yjg4MDQzNDNhXkEyXkFqcGdeQXVyNjIzMzkyMzk@._V1_.jpg","R",6.6,"82 min","Horror, Thriller            ",2016,"Netflix","A deaf and mute writer who retreated into the woods to live a solitary life must fight for her life in silence when a masked killer appears at her window.");
    mvm.addMovie("Baby Driver","https://m.media-amazon.com/images/M/MV5BMjM3MjQ1MzkxNl5BMl5BanBnXkFtZTgwODk1ODgyMjI@._V1_.jpg","R",7.6,"113 min","Action, Crime, Drama            ",2017,"Netflix","After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.");
    mvm.addMovie("Don't Breathe","https://m.media-amazon.com/images/M/MV5BZGI5ZTU2M2YtZWY4MC00ZDFhLTliYTItZTk1NjdlN2NkMzg2XkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_.jpg","R",7.1,"88 min","Crime, Horror, Thriller            ",2016,"Netflix","Hoping to walk away with a massive fortune, a trio of thieves break into the house of a blind man who isn't as helpless as he seems.");
    mvm.addMovie("Spider-Man: Far from Home","https://m.media-amazon.com/images/M/MV5BMGZlNTY1ZWUtYTMzNC00ZjUyLWE0MjQtMTMxN2E3ODYxMWVmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg","PG-13",7.4,"129 min","Action, Adventure, Sci-Fi            ",2019,"Netflix","Following the events of Avengers: Endgame (2019), Spider-Man must step up to take on new threats in a world that has changed forever.");
    mvm.addMovie("Clueless","https://m.media-amazon.com/images/M/MV5BMzBmOGQ0NWItOTZjZC00ZDAxLTgyOTEtODJiYWQ2YWNiYWVjXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_.jpg","PG-13",6.9,"97 min","Comedy, Romance            ",1995,"Netflix","Shallow, rich and socially successful Cher is at the top of her Beverly Hills high school's pecking scale. Seeing herself as a matchmaker, Cher first coaxes two teachers into dating each other.");
    mvm.addMovie("The Devil All the Time","https://m.media-amazon.com/images/M/MV5BZmE1NmVmN2EtMjZmZC00YzAyLWE4MWEtYjY5YmExMjUxODU1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","R",7.1,"138 min","Crime, Drama, Thriller            ",2020,"Netflix","Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town teeming with corruption and brutality.");
    mvm.addMovie("Gunpowder Milkshake","https://m.media-amazon.com/images/M/MV5BYTE4YzczNDQtNmQzNS00ZTZjLThiMzEtOTUzOGQ5ODQzNzY1XkEyXkFqcGdeQXVyMTA3NTQ0Mzkw._V1_.jpg","R",6,"114 min","Action, Crime, Thriller            ",2021,"Netflix","Three generations of women fight back against those who could take everything from them.");
    mvm.addMovie("Fear Street: Part Two - 1978","https://m.media-amazon.com/images/M/MV5BOTQxMWNiZmYtOGUzMi00OGU5LTkzMjctYWY4ZmJkZjZiYWI5XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg","R",6.7,"109 min","Drama, Horror, Mystery            ",2021,"Netflix","Shadyside, 1978. School's out for summer and the activities at Camp Nightwing are about to begin. But when another Shadysider is possessed with the urge to kill, the fun in the sun becomes a gruesome fight for survival.");
    mvm.addMovie("Going in Style","https://m.media-amazon.com/images/M/MV5BMTc5Mzg3NjI4OF5BMl5BanBnXkFtZTgwNzA3Mzg4MDI@._V1_.jpg","PG-13",6.6,"96 min","Comedy, Crime            ",2017,"Netflix","Desperate to pay the bills and come through for their loved ones, three lifelong pals risk it all by embarking on a daring bid to knock off the very bank that absconded with their money.");
    mvm.addMovie("Grease","https://m.media-amazon.com/images/M/MV5BZmUyMDEyOTgtZmUwOS00NTdkLThlNzctNTM1ODQ4M2VhMjdhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg","PG",7.2,"110 min","Musical, Romance            ",1978,"Netflix","Good girl Sandy Olsson and greaser Danny Zuko fell in love over the summer. When they unexpectedly discover they're now in the same high school, will they be able to rekindle their romance?");
    mvm.addMovie("Jaws","https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg","PG",8,"124 min","Adventure, Thriller            ",1975,"Netflix","When a killer shark unleashes chaos on beach community off Long Island, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.");
    mvm.addMovie("The Lord of the Rings: The Return of the King","https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg","PG-13",8.9,"201 min","Action, Adventure, Drama            ",2003,"Netflix","Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.");
    mvm.addMovie("The Next Three Days","https://m.media-amazon.com/images/M/MV5BMjA3NTY5ODI4OV5BMl5BanBnXkFtZTcwMjcxNzQ5Mw@@._V1_.jpg","PG-13",7.3,"133 min","Action, Crime, Drama            ",2010,"Netflix","A married couple's life is turned upside down when the wife is accused of a murder.");
    mvm.addMovie("Taxi Driver","https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg","R",8.2,"114 min","Crime, Drama            ",1976,"Netflix","A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action by attempting to liberate a presidential campaign worker and an underage prostitute.");
    mvm.addMovie("Knock Knock","https://m.media-amazon.com/images/M/MV5BYTQ3MzhlZjQtNWMxOS00NTEzLTgzOWYtNTI3MjhmZGU0ZDM2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg","R",4.9,"99 min","Drama, Thriller            ",2015,"Netflix","A devoted father helps two stranded young women who knock on his door, but his kind gesture turns into a dangerous seduction and a deadly game of cat and mouse.");
    mvm.addMovie("The Revenant","https://m.media-amazon.com/images/M/MV5BMDE5OWMzM2QtOTU2ZS00NzAyLWI2MDEtOTRlYjIxZGM0OWRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg","R",8,"156 min","Action, Adventure, Drama            ",2015,"Netflix","A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.");
    mvm.addMovie("The Irishman","https://m.media-amazon.com/images/M/MV5BMGUyM2ZiZmUtMWY0OC00NTQ4LThkOGUtNjY2NjkzMDJiMWMwXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_.jpg","R",7.8,"209 min","Biography, Crime, Drama            ",2019,"Netflix","Hitman Frank Sheeran looks back at the secrets he kept as a loyal member of the Bufalino crime family.");
    mvm.addMovie("Mother!","https://m.media-amazon.com/images/M/MV5BMzc5ODExODE0MV5BMl5BanBnXkFtZTgwNDkzNDUxMzI@._V1_.jpg","R",6.6,"121 min","Drama, Horror, Mystery            ",2017,"Netflix","A couple's relationship is tested when uninvited guests arrive at their home, disrupting their tranquil existence.");
    mvm.addMovie("Slasher","https://m.media-amazon.com/images/M/MV5BYmNkMjU0ZTAtMGI3Ni00ZDg0LWEwNTQtMDExMWNmYjgzZmI4XkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg","Not Rated",6.7,"60 min","Crime, Drama, Horror            ",2016,"Netflix","An anthology series featuring rampaging serial killers leaving carnage in their wake as their next victims fight to stay alive.");
    mvm.addMovie("Jumanji: The Next Level","https://m.media-amazon.com/images/M/MV5BOTVjMmFiMDUtOWQ4My00YzhmLWE3MzEtODM1NDFjMWEwZTRkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","PG-13",6.7,"123 min","Action, Adventure, Comedy            ",2019,"Netflix","In Jumanji: The Next Level, the gang is back but the game has changed. As they return to rescue one of their own, the players will have to brave parts unknown from arid deserts to snowy mountains, to escape the world's most dangerous game.");
    mvm.addMovie("Wind River","https://m.media-amazon.com/images/M/MV5BMTUyMjU1OTUwM15BMl5BanBnXkFtZTgwMDg1NDQ2MjI@._V1_.jpg","R",7.7,"107 min","Crime, Drama, Mystery            ",2017,"Netflix","A veteran hunter helps an FBI agent investigate the murder of a young woman on a Wyoming Native American reservation.");
    mvm.addMovie("The Holiday","https://m.media-amazon.com/images/M/MV5BMTI1MDk4MzA2OF5BMl5BanBnXkFtZTYwMjQ3NDc3._V1_.jpg","PG-13",6.9,"136 min","Comedy, Romance            ",2006,"Netflix","Two women troubled with guy-problems swap homes in each other's countries, where they each meet a local guy and fall in love.");
    mvm.addMovie("Kill Bill: Vol. 1","https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg","R",8.1,"111 min","Action, Crime, Drama            ",2003,"Netflix","After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.");
    mvm.addMovie("News of the World","https://m.media-amazon.com/images/M/MV5BMDNlNmVlNDItMjE3Yi00ZTA3LWIyOTktNDhhMGFlZjk5ZDQ0XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg","PG-13",6.8,"118 min","Action, Adventure, Drama            ",2020,"Netflix","A Civil War veteran agrees to deliver a girl, taken by the Kiowa people years ago, to her aunt and uncle, against her will. They travel hundreds of miles and face grave dangers as they search for a place that either can call home.");
    mvm.addMovie("Spirited Away","https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg","PG",8.6,"125 min","Animation, Adventure, Family            ",2001,"Netflix","During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.");
    mvm.addMovie("300","https://m.media-amazon.com/images/M/MV5BNWMxYTZlOTUtZDExMi00YzZmLTkwYTMtZmM2MmRjZmQ3OGY4XkEyXkFqcGdeQXVyMTAwMzUyMzUy._V1_.jpg","R",7.6,"117 min","Action, Drama            ",2006,"Netflix","King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.");
    mvm.addMovie("My Little Pony: A New Generation","https://m.media-amazon.com/images/M/MV5BZjUzZjliYjgtYjNkZC00OThhLTg1OTItZjgzNjY4Yzg0ZTQ2XkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_.jpg","PG",6.9,"90 min","Animation, Adventure, Comedy            ",2021,"Netflix","After the time of the Mane 6, Sunny--a young Earth Pony--and her new Unicorn friend Izzy explore their world and strive to restore Harmony to Equestria.");
    mvm.addMovie("Snowpiercer","https://m.media-amazon.com/images/M/MV5BMTQ3NzA1MTY3MV5BMl5BanBnXkFtZTgwNzE2Mzg5MTE@._V1_.jpg","R",7.1,"126 min","Action, Drama, Sci-Fi            ",2013,"Netflix","In a future where a failed climate change experiment has killed all life except for the survivors who boarded the Snowpiercer (a train that travels around the globe), a new class system emerges.");
    mvm.addMovie("National Lampoon's Animal House","https://m.media-amazon.com/images/M/MV5BM2M2ZDA4MTYtOGRjMi00OTg5LWI1ZTUtMjQxZTc2NWZjNDFkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg","R",7.5,"109 min","Comedy            ",1978,"Netflix","At a 1962 college, Dean Vernon Wormer is determined to expel the entire Delta Tau Chi Fraternity, but those troublemakers have other plans for him.");
    mvm.addMovie("The Lost Daughter","https://m.media-amazon.com/images/M/MV5BZTJmYTJmYTktMzU1Yy00ZTZlLTgzNjItYmY4ZDFjZGFjYjZhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg","R",6.6,"121 min","Drama            ",2021,"Netflix","A woman's beach vacation takes a dark turn when she begins to confront the troubles of her past.");
    mvm.addMovie("Baywatch","https://m.media-amazon.com/images/M/MV5BNTA4MjQ0ODQzNF5BMl5BanBnXkFtZTgwNzA5NjYzMjI@._V1_.jpg","R",5.5,"116 min","Action, Comedy, Crime            ",2017,"Netflix","Devoted lifeguard Mitch Buchannon butts heads with a brash new recruit, as they uncover a criminal plot that threatens the future of the bay.");
    mvm.addMovie("Child's Play","https://m.media-amazon.com/images/M/MV5BNTNlNjIxNjktOWUyMS00YWY5LWEwZGItMjZmODJlZWNiZGM2XkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_.jpg","R",5.7,"90 min","Drama, Horror, Sci-Fi            ",2019,"Netflix","A mother gives her 13-year-old son a toy doll for his birthday, unaware of its more sinister nature.");
    mvm.addMovie("The Hobbit: An Unexpected Journey","https://m.media-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_.jpg","PG-13",7.8,"169 min","Adventure, Fantasy            ",2012,"Netflix","A reluctant Hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home, and the gold within it from the dragon Smaug.");
    mvm.addMovie("Charlie's Angels","https://m.media-amazon.com/images/M/MV5BN2VkMjQwZWMtMzc1NC00ZjJiLWJlNTMtNmRjOTE2ZTJmYzUwXkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_.jpg","PG-13",4.9,"118 min","Action, Adventure, Comedy            ",2019,"Netflix","When a young systems engineer blows the whistle on a dangerous technology, Charlie's Angels are called into action, putting their lives on the line to protect us all.");
    mvm.addMovie("Rosemary's Baby","https://m.media-amazon.com/images/M/MV5BZmEwZGU2NzctYzlmNi00MGJkLWE3N2MtYjBlN2ZhMGJkZTZiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg","Approved",8,"137 min","Drama, Horror            ",1968,"Netflix","A young couple trying for a baby move into an aging, ornate apartment building on Central Park West, but find themselves surrounded by peculiar neighbors.");
    mvm.addMovie("Legally Blonde","https://m.media-amazon.com/images/M/MV5BNTEyNjUwMTkxMV5BMl5BanBnXkFtZTcwNjk0NDk0NA@@._V1_.jpg","PG-13",6.4,"96 min","Comedy, Romance            ",2001,"Netflix","Elle Woods, a fashionable sorority queen, is dumped by her boyfriend. She decides to follow him to law school. While she is there, she figures out that there is more to her than just looks.");
    mvm.addMovie("Annihilation","https://m.media-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_.jpg","R",6.8,"115 min","Adventure, Drama, Horror            ",2018,"Netflix","A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don't apply.");
    mvm.addMovie("A Knight's Tale","https://m.media-amazon.com/images/M/MV5BMTE5OTE4OTE2Nl5BMl5BanBnXkFtZTYwMDkzMTQ3._V1_.jpg","PG-13",6.9,"132 min","Action, Adventure, Romance            ",2001,"Netflix","After his master dies, a peasant squire, fueled by his desire for food and glory, creates a new identity for himself as a knight.");
    mvm.addMovie("Uncut Gems","https://m.media-amazon.com/images/M/MV5BZDhkMjUyYjItYWVkYi00YTM5LWE4MGEtY2FlMjA3OThlYmZhXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg","R",7.4,"135 min","Crime, Drama, Thriller            ",2019,"Netflix","With his debts mounting and angry collectors closing in, a fast-talking New York City jeweler risks everything in hope of staying afloat and alive.");
    mvm.addMovie("Step Brothers","https://m.media-amazon.com/images/M/MV5BODViZDg3ZjYtMzhiYS00YTVkLTk4MzktYWUxMTlkYjc1NjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg","R",6.9,"98 min","Comedy            ",2008,"Netflix","Two aimless middle-aged losers still living at home are forced against their will to become roommates when their parents marry.");
    mvm.addMovie("The Lord of the Rings: The Two Towers","https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg","PG-13",8.7,"179 min","Action, Adventure, Drama            ",2002,"Netflix","While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.");
    mvm.addMovie("6 Underground","https://m.media-amazon.com/images/M/MV5BNzE2ZjQxNjEtNmI2ZS00ZmU0LTg4M2YtYzVhYmRiYWU0YzI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","R",6.1,"128 min","Action, Thriller            ",2019,"Netflix","Six individuals from all around the globe, each the very best at what they do, have been chosen not only for their skill, but for a unique desire to delete their pasts to change the future.");
    mvm.addMovie("Escape Room","https://m.media-amazon.com/images/M/MV5BMjQ2NDMwMTY3MF5BMl5BanBnXkFtZTgwNDg5OTc1NjM@._V1_.jpg","PG-13",6.4,"99 min","Action, Adventure, Horror            ",2019,"Netflix","Six strangers find themselves in a maze of deadly mystery rooms and must use their wits to survive.");
    mvm.addMovie("Pirates of the Caribbean: Dead Men Tell No Tales","https://m.media-amazon.com/images/M/MV5BMTYyMTcxNzc5M15BMl5BanBnXkFtZTgwOTg2ODE2MTI@._V1_.jpg","PG-13",6.5,"129 min","Action, Adventure, Fantasy            ",2017,"Netflix","Captain Jack Sparrow is pursued by old rival Captain Salazar and a crew of deadly ghosts who have escaped from the Devil's Triangle. They're determined to kill every pirate at sea...notably Jack.");
    mvm.addMovie("Sweet Girl","https://m.media-amazon.com/images/M/MV5BOGIzOTZiZjItNTMyYS00ODcyLWE2ZDUtYWNjZDNmNTUxYjVkXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg","R",5.5,"110 min","Action, Drama, Thriller            ",2021,"Netflix","A devastated husband vows to bring justice to the people responsible for his wife's death while protecting the only family he has left, his daughter.");
    mvm.addMovie("Captain America: Civil War","https://m.media-amazon.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_.jpg","PG-13",7.8,"147 min","Action, Adventure, Sci-Fi            ",2016,"Netflix","Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.");
    mvm.addMovie("2001: A Space Odyssey","https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg","G",8.3,"149 min","Adventure, Sci-Fi            ",1968,"Netflix","After discovering a mysterious artifact buried beneath the Lunar surface, mankind sets off on a quest to find its origins with help from intelligent supercomputer H.A.L. 9000.");
    mvm.addMovie("The Hitman's Bodyguard","https://m.media-amazon.com/images/M/MV5BMjQ5NjA2NDg1MV5BMl5BanBnXkFtZTgwMDAzNDc4MjI@._V1_.jpg","R",6.9,"118 min","Action, Comedy, Crime            ",2017,"Netflix","The world's top bodyguard gets a new client, a hitman who must testify at the International Criminal Court. They must put their differences aside and work together to make it to the trial on time.");
    mvm.addMovie("Howl's Moving Castle","https://m.media-amazon.com/images/M/MV5BNmM4YTFmMmItMGE3Yy00MmRkLTlmZGEtMzZlOTQzYjk3MzA2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg","PG",8.2,"119 min","Animation, Adventure, Family            ",2004,"Netflix","When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.");
    mvm.addMovie("Beauty and the Beast","https://m.media-amazon.com/images/M/MV5BMTUwNjUxMTM4NV5BMl5BanBnXkFtZTgwODExMDQzMTI@._V1_.jpg","PG",7.1,"129 min","Adventure, Family, Fantasy            ",2017,"Netflix","A selfish Prince is cursed to become a monster for the rest of his life, unless he learns to fall in love with a beautiful young woman he keeps prisoner.");
    mvm.addMovie("Love and Monsters","https://m.media-amazon.com/images/M/MV5BYWVkMWEyMDUtZTVmOC00MTYxLWE1ZTUtNjk4M2IzMjY2OTIxXkEyXkFqcGdeQXVyMDk5Mzc5MQ@@._V1_.jpg","PG-13",7,"109 min","Action, Adventure, Comedy            ",2020,"Netflix","Seven years after he survived the monster apocalypse, lovably hapless Joel leaves his cozy underground bunker behind on a quest to reunite with his ex.");
    mvm.addMovie("StartUp","https://m.media-amazon.com/images/M/MV5BMTAxNTIwNzE5MTJeQTJeQWpwZ15BbWU4MDE2NDQ2MTMy._V1_.jpg","Not Rated",7.9,"44 min","Crime, Thriller            ",20162018,"Netflix","A desperate banker, a Haitian-American gang lord and a Cuban-American hacker are forced to work together to unwittingly create their version of the American dream - organized crime 2.0.");
    mvm.addMovie("Mars Attacks!","https://m.media-amazon.com/images/M/MV5BNThlMjBmOWItNjljZi00ZGU4LWJkZjgtNWU1ZjI1MTg4MzczXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg","PG-13",6.3,"106 min","Comedy, Sci-Fi            ",1996,"Netflix","Earth is invaded by Martians with unbeatable weapons and a cruel sense of humor.");
    mvm.addMovie("Willy Wonka & the Chocolate Factory","https://m.media-amazon.com/images/M/MV5BZTllNDU0ZTItYTYxMC00OTI4LThlNDAtZjNiNzdhMWZiYjNmXkEyXkFqcGdeQXVyNzY1NDgwNjQ@._V1_.jpg","G",7.8,"100 min","Family, Fantasy, Musical            ",1971,"Netflix","A poor but hopeful boy seeks one of the five coveted golden tickets that will send him on a tour of Willy Wonka's mysterious chocolate factory.");
    mvm.addMovie("Batman v Superman: Dawn of Justice","https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg","PG-13",6.4,"152 min","Action, Adventure, Sci-Fi            ",2016,"Netflix","Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.");
    mvm.addMovie("Tommy Boy","https://m.media-amazon.com/images/M/MV5BNTMwZGU3MGUtZWE0Ni00YzExLWIyY2MtMmNmMDlmYTdmNzFkXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_.jpg","PG-13",7.1,"97 min","Adventure, Comedy            ",1995,"Netflix","After his auto-parts tycoon father dies, the overweight, underachieving son teams up with a snide accountant to try and save the family business.");
    mvm.addMovie("Jumanji: Welcome to the Jungle","https://m.media-amazon.com/images/M/MV5BODQ0NDhjYWItYTMxZi00NTk2LWIzNDEtOWZiYWYxZjc2MTgxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg","PG-13",6.9,"119 min","Action, Adventure, Comedy            ",2017,"Netflix","Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.");
    mvm.addMovie("Vivo","https://m.media-amazon.com/images/M/MV5BOTYyMzliZjMtYjI4NC00OTI4LThlZmMtZGQ1MmFhMmE5MDEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","PG",6.7,"95 min","Animation, Adventure, Comedy            ",2021,"Netflix","Vivo, Sony Pictures Animation's first-ever musical adventure featuring all-new original songs from Lin-Manuel Miranda, will take audiences on an epic adventure to gorgeous and vibrant locations never before seen in animation.");
    mvm.addMovie("SAS: Red Notice","https://m.media-amazon.com/images/M/MV5BYzVjMWU4OGUtNGEyZS00MjJiLWIzNTMtNDk1NDdmMDUwYTAyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg","R",5.2,"124 min","Action, Thriller            ",2021,"Netflix","A small army of well trained criminals led by Grace Lewis have hijacked a train deep beneath the English Channel.");
    mvm.addMovie("I Care a Lot","https://m.media-amazon.com/images/M/MV5BN2M3ZDhhMDItNjk0ZC00NGFhLTk0NDEtYzA2OWIzMmI2Yzg3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg","R",6.3,"118 min","Comedy, Crime, Thriller            ",2020,"Netflix","A crooked legal guardian who drains the savings of her elderly wards meets her match when a woman she tries to swindle turns out to be more than she first appears.");
    mvm.addMovie("Frozen","https://m.media-amazon.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_.jpg","PG",7.4,"102 min","Animation, Adventure, Comedy            ",2013,"Netflix","When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.");
    mvm.addMovie("Dead Poets Society","https://m.media-amazon.com/images/M/MV5BOGYwYWNjMzgtNGU4ZC00NWQ2LWEwZjUtMzE1Zjc3NjY3YTU1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg","PG",8.1,"128 min","Comedy, Drama            ",1989,"Netflix","Maverick teacher John Keating uses poetry to embolden his boarding school students to new heights of self-expression.");
    mvm.addMovie("Monster Hunter","https://m.media-amazon.com/images/M/MV5BYjA5OTRmODQtY2Y2Ni00Nzk2LTlkNjEtM2E1OWNkMjQzZjE4XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg","PG-13",5.3,"103 min","Action, Adventure, Fantasy            ",2020,"Netflix","When Cpt. Artemis and her loyal soldiers are transported to a new world, they engage in a desperate battle for survival against enormous enemies with incredible powers. Feature film based on the video game by Capcom.");
    mvm.addMovie("Ghost","https://m.media-amazon.com/images/M/MV5BMmE4ZjI3YzctNjM0YS00MjBlLWFmYjItNDRiNTk0ZmRkYjVjXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_.jpg","PG-13",7.1,"127 min","Drama, Fantasy, Romance            ",1990,"Netflix","After a young man is murdered, his spirit stays behind to warn his lover of impending danger, with the help of a reluctant psychic.");
    mvm.addMovie("Enola Holmes","https://m.media-amazon.com/images/M/MV5BZjNkNzk0ZjEtM2M1ZC00MmMxLTlmOWEtNWRlZTc1ZTUyNzY4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg","PG-13",6.6,"123 min","Action, Adventure, Crime            ",2020,"Netflix","When Enola Holmes-Sherlock's teen sister-discovers her mother missing, she sets off to find her, becoming a super-sleuth in her own right as she outwits her famous brother and unravels a dangerous conspiracy around a mysterious young Lord.");
    mvm.addMovie("Marriage Story","https://m.media-amazon.com/images/M/MV5BZGVmY2RjNDgtMTc3Yy00YmY0LTgwODItYzBjNWJhNTRlYjdkXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg","R",7.9,"137 min","Comedy, Drama, Romance            ",2019,"Netflix","Noah Baumbach's incisive and compassionate look at a marriage breaking up and a family staying together.");
    mvm.addMovie("Your Name.","https://m.media-amazon.com/images/M/MV5BYjAxOGE2YmEtZjc4MS00ZjcxLWI5NTMtNDA2ZGU5ODQ4NTBmXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg","PG",8.4,"106 min","Animation, Drama, Fantasy            ",2016,"Netflix","Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?");
    mvm.addMovie("The Mitchells vs the Machines","https://m.media-amazon.com/images/M/MV5BMjdkZjNjNDItYzc4MC00NTkxLTk1MWEtY2UyZjY5MjUwNDNkXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_.jpg","PG",7.7,"113 min","Animation, Adventure, Comedy            ",2021,"Netflix","A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.");
    mvm.addMovie("Contagion","https://m.media-amazon.com/images/M/MV5BMTY3MDk5MDc3OV5BMl5BanBnXkFtZTcwNzAyNTg0Ng@@._V1_.jpg","PG-13",6.8,"106 min","Drama, Thriller            ",2011,"Netflix","Healthcare professionals, government officials and everyday people find themselves in the midst of a pandemic as the CDC works to find a cure.");
    mvm.addMovie("Hotel Transylvania 3: Summer Vacation","https://m.media-amazon.com/images/M/MV5BNjA1MzU5MTY3OF5BMl5BanBnXkFtZTgwNTU5MDA3NTM@._V1_.jpg","PG",6.3,"97 min","Animation, Adventure, Comedy            ",2018,"Netflix","Count Dracula and company participate in a cruise for sea-loving monsters, unaware that their boat is being commandeered by the monster-hating Van Helsing family.");
    mvm.addMovie("Vincenzo","https://m.media-amazon.com/images/M/MV5BYWIwYTg2Y2YtYzEwNy00Y2Y0LWFkZjktNjBlMWZhNDY2NGE0XkEyXkFqcGdeQXVyNDY5MjMyNTg@._V1_.jpg","Not Rated",8.5,"80 min","Comedy, Crime, Romance            ",2021,"Netflix","During a visit to his motherland, a Korean-Italian mafia lawyer gives an unrivaled conglomerate a taste of its own medicine with a side of justice.");
  }

}